import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './style/global.css'
import { ReduxProvider } from '@/Redux/Providrer'
 import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>

      <ReduxProvider >
        {children}
      </ReduxProvider>
        </AppRouterCacheProvider>
        </body>


    </html>
  )
}
